# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.hostname = "ubuntu-2004-arm64"

  config.vm.box = "turknet-devops/ubuntu-20.04"
  config.vm.box_version = "0.0.2"

  config.vm.network :private_network, ip: "172.16.10.210", dhcp: false, bridge: "enp0s8"


  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "../../vagrant/", "/vagrant", privileged: true

  config.vm.provision "shell", inline: "cat /vagrant/keys/vagrant_id_rsa.pub >> /home/vagrant/.ssh/authorized_keys", privileged: false
  config.vm.provision "shell", inline: "echo 'cd /vagrant' >> ~/.bashrc", privileged: false

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true

  config.vm.provider :parallels do |box|
    box.memory = 4096
    box.cpus = 4
    box.name = "ubuntu-20.04-arm64"
    box.linked_clone = false
    box.update_guest_tools = true

    config.ssh.username = 'vagrant'
    config.ssh.password = 'vagrant'
    config.ssh.insert_key = 'false'
  end

  config.vm.provision "shell", inline: "echo Hello, World"

end